### ISSUE TITLE
Error 0x80101104

### ISSUE THREAD

**Issue by zenogears** [SonicMastr/godot-vita#26] opened 2023-03-25 21:05 UTC
Godot version:
3.5
OS/device including version:
Linux
Issue description:
Package does not install
Steps to reproduce:
Build and install with VitaShell

**Comment by zenogears** [comment] 2023-03-25 22:53
VPK file: https://mega.nz/file/TI5DXKyJ#jO3NfwXuxvsa_nGBtXNEGKI1adbdQ3A0L8BqTIOb_gc
project:  https://mega.nz/file/OA4WXZpY#kn6X9tzVc-tfD_qO-jb6c-qUqLXEfDnL7pTX-12xMO8

**Comment by SonicMastr** [comment] 2023-04-05 22:02
Duplicate of #14 and #22. Was already fixed in a302d4b725791d4b1d5f2d8c76bcf4d3a4da7ebd

**Closed by SonicMastr** 2023-04-05 22:02 UTC
Labels: duplicate

**Comment by zenogears** [comment] 2023-04-11 19:12
@SonicMastr Hi! So fixed in new version. But where i can download godot with fixed tools?

**Comment by SonicMastr** [comment] 2023-04-11 20:39
You can get the Vita Template here: https://github.com/SonicMastr/godot-vita/actions/runs/4623774966
And the Windows build of Godot here: https://github.com/SonicMastr/godot-vita/actions/runs/4623774984
Linux: https://github.com/SonicMastr/godot-vita/actions/runs/4623774963
OSX: https://github.com/SonicMastr/godot-vita/actions/runs/4623774964

**Comment by zenogears** [comment] 2023-04-12 08:55
> You can get the Vita Template here: https://github.com/SonicMastr/godot-vita/actions/runs/4623774966
How to install it? Rename to *.tpz and import as export template? It says that version.txt not found :(
> And the Linux: https://github.com/SonicMastr/godot-vita/actions/runs/4623774963
With mono? :( 
> Remember, this is 3.6 beta
Yap, 3.6 is good. Not 4.0.2, but if it will works....

**Comment by SonicMastr** [comment] 2023-04-12 09:15
Mono is not supported. For the template, you need to put the artifact and a version.txt into a tpz archive (just a zip renamed)

**Comment by zenogears** [comment] 2023-04-13 22:42
Thanks! It works.
Maybe create some instruction for people who want new version?

**Comment by meigel** [comment] 2023-04-16 23:00
I can't get it to work... Trying to install exported VPK gives error 0x80101130.

**Comment by zenogears** [comment] 2023-04-17 09:54
@meigel 
Use Godot from this comment: https://github.com/SonicMastr/godot-vita/issues/26#issuecomment-1504060182
And use Template binaries for it from here: https://github.com/SonicMastr/godot-vita/actions/runs/4623774966
Instruction how to from zip template bitaries create Godot Vita Template: https://github.com/SonicMastr/godot-vita/issues/26#issuecomment-1504938774

**Comment by meigel** [comment] 2023-04-17 17:54
Seems to work now. The problem was an apparently incompatible png included in the project. Any hints where to find information about what image files can be used, in particular as textures in 3D?

@SonicMastr It's amazing to have this tool for the Vita!

**Comment by Bunkai9448** [comment] 2024-03-29 11:58
Can confirm it's fixed in the updated version 3.6.beta from a few days found at (artifacts from)
https://github.com/SonicMastr/godot-vita/actions/runs/8011699088

**Comment by Lumexio** [comment] 2026-04-09 07:59
H

> You can get the Vita Template here: https://github.com/SonicMastr/godot-vita/actions/runs/4623774966 And the Windows build of the Godot editor here: https://github.com/SonicMastr/godot-vita/actions/runs/4623774984 Linux: https://github.com/SonicMastr/godot-vita/actions/runs/4623774963 OSX: https://github.com/SonicMastr/godot-vita/actions/runs/4623774964
> 
> Remember, this is 3.6 beta

So the resources you provided are not longer available, where can i find the template to export my vpk's?
and the editor too?!!! :c
